var f;f||=typeof Module != 'undefined' ? Module : {};var aa=Object.assign({},f),ba=[],ca="./this.program",da=(a,b)=>{throw b;},h="";"undefined"!=typeof document&&document.currentScript&&(h=document.currentScript.src);h=h.startsWith("blob:")?"":h.substr(0,h.replace(/[?#].*/,"").lastIndexOf("/")+1);var ea=f.print||console.log.bind(console),k=f.printErr||console.error.bind(console);Object.assign(f,aa);aa=null;f.arguments&&(ba=f.arguments);f.thisProgram&&(ca=f.thisProgram);
f.quit&&(da=f.quit);var fa;f.wasmBinary&&(fa=f.wasmBinary);var ha,n=!1,ia,ja,q,ka,r,v,x,la,ma=[],na=[],oa=[],pa=[];function qa(){var a=f.preRun.shift();ma.unshift(a)}var z=0,ra=null,sa=null;function ta(a){f.onAbort?.(a);a="Aborted("+a+")";k(a);n=!0;ia=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua=a=>a.startsWith("data:application/octet-stream;base64,"),va;
function wa(a){if(a==va&&fa)return new Uint8Array(fa);throw"both async and sync fetching of the wasm failed";}function xa(a){return fa||"function"!=typeof fetch?Promise.resolve().then(()=>wa(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>wa(a))}function ya(a,b,c){return xa(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{k(`failed to asynchronously prepare wasm: ${d}`);ta(d)})}
function za(a,b){var c=va;fa||"function"!=typeof WebAssembly.instantiateStreaming||ua(c)||"function"!=typeof fetch?ya(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){k(`wasm streaming compile failed: ${e}`);k("falling back to ArrayBuffer instantiation");return ya(c,a,b)}))}function Aa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ba=a=>{for(;0<a.length;)a.shift()(f)},Ca=f.noExitRuntime||!0,Da=a=>0===a%4&&(0!==a%100||0===a%400),Ea=[0,31,60,91,121,152,182,213,244,274,305,335],Fa=[0,31,59,90,120,151,181,212,243,273,304,334],A=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);if(55296<=l&&57343>=l){var p=a.charCodeAt(++g);l=65536+((l&1023)<<10)|p&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|
l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e},Ga=0,Ha=[];function Ia(){if(navigator.userActivation?navigator.userActivation.isActive:Ga&&Ja.Ee)for(var a=0;a<Ha.length;++a){var b=Ha[a];Ha.splice(a,1);--a;b.nf(...b.Ge)}}var C=[];function Ka(a){var b=C[a];b.target.removeEventListener(b.$c,b.Ed,b.be);C.splice(a,1)}
function La(a){if(!a.target)return-4;if(a.he)a.Ed=function(c){++Ga;Ja=a;Ia();a.oe(c);Ia();--Ga},a.target.addEventListener(a.$c,a.Ed,a.be),C.push(a);else for(var b=0;b<C.length;++b)C[b].target==a.target&&C[b].$c==a.$c&&Ka(b--);return 0}
var Ja,Ma,Na="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,D=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Na)return Na.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|l:(e&7)<<18|g<<12|l<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Oa=[0,document,window],Pa=a=>{a=2<a?a?D(q,a):"":a;return Oa[a]||document.querySelector(a)},Qa=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,l)=>b.drawElementsInstancedANGLE(c,d,e,g,l))},Ra=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Sa=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Ta=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Ua=1,Va=[],E=[],Wa=[],F=[],G=[],H=[],Xa=[],Ya=[],I=[],Za={},$a=4,ab=a=>{for(var b=Ua++,c=a.length;c<b;c++)a[c]=null;return b},bb=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=J[c](),l=g&&ab(d);g?(g.name=l,d[l]=g):K||=1282;r[b+4*e>>2]=l}},db=(a,b)=>{a.Dd||(a.Dd=a.getContext,a.getContext=function(d,e){e=a.Dd(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?cb(c,b):0},cb=(a,b)=>{var c=ab(Ya),
d={handle:c,attributes:b,version:b.qe,pd:a};a.canvas&&(a.canvas.De=d);Ya[c]=d;("undefined"==typeof b.ne||b.ne)&&eb(d);return c},eb=a=>{a||=fb;if(!a.pe){a.pe=!0;var b=a.pd;Qa(b);Ra(b);Sa(b);b.Lc=b.getExtension("EXT_disjoint_timer_query");b.We=b.getExtension("WEBGL_multi_draw");Ta(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},gb={},K,fb,hb=[],ib=(a,b,c,d,e,g,l,p)=>{b=E[b];if(a=J[a](b,c))d=p&&A(a.name,q,p,d),e&&(r[e>>2]=d),g&&(r[g>>2]=a.size),l&&(r[l>>2]=a.type)},
jb=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(K||=1280);return;case 36345:d=0;break;case 34466:var e=J.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=J.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":K||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:K||=1280;return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:r[b+4*a>>2]=e[a];break;case 2:x[b+4*a>>2]=e[a];break;case 4:ja[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(g){K||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${g})`);return}}break;default:K||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=
d;v[b>>2]=c;v[b+4>>2]=(c-v[b>>2])/4294967296;break;case 0:r[b>>2]=d;break;case 2:x[b>>2]=d;break;case 4:ja[b]=d?1:0}}else K||=1281},kb=(a,b,c)=>{if(c){a=J.Lc.getQueryObjectEXT(I[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d;v[c+4>>2]=(d-v[c>>2])/4294967296}else K||=1281},lb=(a,b,c)=>{if(c){a=J.Lc.getQueryObjectEXT(I[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;r[c>>2]=d}else K||=1281},mb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=
4,++c):b+=3}return b},L=a=>{var b=mb(a)+1,c=nb(b);c&&A(a,q,c,b);return c};function ob(){var a=Ta(J);return a=a.concat(a.map(b=>"GL_"+b))}
var pb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),qb=a=>{var b=a.Vc,c=a.ae,d;if(!b)for(a.Vc=b={},a.$d={},d=0;d<J.getProgramParameter(a,35718);++d){var e=J.getActiveUniform(a,d);var g=e.name;e=e.size;var l=pb(g);l=0<l?g.slice(0,l):g;var p=a.Ad;a.Ad+=e;c[l]=[e,p];for(g=0;g<e;++g)b[p]=g,a.$d[p++]=l}},M=a=>{var b=J.je;if(b){var c=b.Vc[a];"number"==typeof c&&(b.Vc[a]=c=J.getUniformLocation(b,b.$d[a]+(0<c?`[${c}]`:"")));return c}K||=1282},rb=(a,b,c,d)=>{if(c)if(a=E[a],qb(a),a=J.getUniform(a,M(b)),"number"==
typeof a||"boolean"==typeof a)switch(d){case 0:r[c>>2]=a;break;case 2:x[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:r[c+4*b>>2]=a[b];break;case 2:x[c+4*b>>2]=a[b]}else K||=1281},sb=(a,b,c,d)=>{if(c)if(a=J.getVertexAttrib(a,b),34975==b)r[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:r[c>>2]=a;break;case 2:x[c>>2]=a;break;case 5:r[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:r[c+4*b>>2]=a[b];break;case 2:x[c+4*b>>2]=a[b];break;case 5:r[c+
4*b>>2]=Math.fround(a[b])}else K||=1281},tb=(a,b,c,d,e)=>{a-=5120;a=1==a?q:4==a?r:6==a?x:5==a||28922==a?v:ka;var g=$a;b=d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+g-1&-g);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},N=[],ub=[],vb=a=>{a instanceof Aa||"unwind"==a||da(1,a)},wb=a=>{ia=a;Ca||(f.onExit?.(a),n=!0);da(a,new Aa(a))},xb=a=>{ia=a;wb(a)},yb=!1,O=null,P=0,zb=null,Ab=0,Bb=0,Cb=0,Q=0,Db=[],Eb={},Fb,Gb,Hb,R=!1,Ib=!1,
Jb=[];
function Kb(){function a(){Ib=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}if(!Lb){Lb=!0;var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",c=>{!Ib&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Mb(a,b,c,d){if(b&&f.Qc&&a==f.canvas)return f.Qc;var e;if(b){var g={antialias:!1,alpha:!1,qe:1};if(d)for(var l in d)g[l]=d[l];if("undefined"!=typeof gb&&(e=db(a,g)))var p=Ya[e].pd}else p=a.getContext("2d");if(!p)return null;c&&(f.Qc=p,b&&(fb=Ya[e],f.Qc=J=fb?.pd),f.rf=b,Jb.forEach(t=>t()),Kb());return p}var Nb=!1,T=void 0,U=void 0;
function Ob(a,b){function c(){R=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Pb,T&&d.requestPointerLock(),R=!0,U?Qb():V(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),U?Rb():V(d));f.onFullScreen?.(R);f.onFullscreen?.(R)}T=a;U=b;"undefined"==typeof T&&(T=!0);"undefined"==typeof U&&(U=!1);var d=f.canvas;Nb||(Nb=!0,document.addEventListener("fullscreenchange",
c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):
null);e.requestFullscreen()}function Pb(){if(!R)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Sb=0;function Tb(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Sb)Sb=b+1E3/60;else for(;b+2>=Sb;)Sb+=1E3/60;setTimeout(a,Math.max(Sb-b,0))}}var Ub=0,Vb=0,Wb=0,Xb=0;
function Yb(a,b){var c=f.canvas.getBoundingClientRect(),d=f.canvas.height;a-=("undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset)+c.left;b-=("undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset)+c.top;a*=f.canvas.width/c.width;b*=d/c.height;return{x:a,y:b}}function Zb(a,b){const {x:c,y:d}=Yb(a,b);Wb=c-Ub;Xb=d-Vb;Ub=c;Vb=d}
function cc(a){Ib?("mousemove"!=a.type&&"mozMovementX"in a?Wb=Xb=0:(Wb=a.movementX||a.mozMovementX||a.webkitMovementX||0,Xb=a.movementY||a.mozMovementY||a.webkitMovementY||0),Ub+=Wb,Vb+=Xb):"touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type?(a=a.qf,void 0!==a&&Yb(a.pageX,a.pageY)):Zb(a.pageX,a.pageY)}var dc=[];function ec(){var a=f.canvas;dc.forEach(b=>b(a.width,a.height))}function fc(a,b,c){V(f.canvas,a,b);c||ec()}
function Qb(){"undefined"!=typeof SDL&&(r[SDL.screen>>2]=v[SDL.screen>>2]|8388608);V(f.canvas);ec()}function Rb(){"undefined"!=typeof SDL&&(r[SDL.screen>>2]=v[SDL.screen>>2]&-8388609);V(f.canvas);ec()}
function V(a,b,c){b&&c?(a.Cd=b,a.td=c):(b=a.Cd,c=a.td);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}U?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Lb,gc,ic=(a,b)=>{Bb=a;Cb=b;if(zb)if(yb||=!0,0==a)O=function(){var d=Math.max(0,Gb+b-hc())|0;setTimeout(Hb,d)};else if(1==a)O=function(){Tb(Hb)};else if(2==a){if("undefined"==typeof gc)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);gc=function(d){c.push(d);postMessage("setimmediate","*")}}else gc=setImmediate;O=function(){gc(Hb)}}},hc;hc=()=>performance.now();
var jc=(a,b,c,d,e)=>{zb=a;Ab=d;var g=P;yb=!1;Hb=function(){if(!n)if(0<Db.length){var l=Db.shift();l.Ne(l.Fe);if(Fb){var p=Fb,t=0==p%1?p-1:Math.floor(p);Fb=l.Je?t:(8*p+(t+.5))/9}f.setStatus&&(l=f.statusMessage||"Please wait...",p=Fb,t=Eb.Le,p?p<t?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));g<P||setTimeout(Hb,0)}else if(!(g<P))if(Q=Q+1|0,1==Bb&&1<Cb&&0!=Q%Cb)O();else{0==Bb&&(Gb=hc());if(!(n||f.preMainLoop&&!1===f.preMainLoop())){if(!n)try{if(a(),!Ca)try{ia=
l=ia,wb(l)}catch(y){vb(y)}}catch(y){vb(y)}f.postMainLoop?.()}g<P||("object"==typeof SDL&&SDL.audio?.Xe?.(),O())}};e||(b&&0<b?ic(0,1E3/b):ic(1,1),O());if(c)throw"unwind";},kc=[],lc,W=a=>{var b=kc[a];b||(a>=kc.length&&(kc.length=a+1),kc[a]=b=lc.get(a));return b},mc=(a,b,c,d)=>{Ma||=nb(36);a=Pa(a);return La({target:a,$c:"resize",he:d,oe:(e=event)=>{if(e.target==a){var g=document.body;if(g){var l=Ma;r[l>>2]=0;r[l+4>>2]=g.clientWidth;r[l+8>>2]=g.clientHeight;r[l+12>>2]=innerWidth;r[l+16>>2]=innerHeight;
r[l+20>>2]=outerWidth;r[l+24>>2]=outerHeight;r[l+28>>2]=pageXOffset|0;r[l+32>>2]=pageYOffset|0;W(d)(10,l,b)&&e.preventDefault()}}},be:c})},nc=[null,[],[]];
function oc(a,b,c,d,e,g){this.id=a;this.y=this.x=0;this.ad=!1;this.Zd=this.Yd=0;this.width=b;this.height=c;this.sd=d;this.rd=e;this.yd=b;this.xd=c;this.title=g;this.attributes=Object.assign({},X.Mc);this.Id={208897:212993,208898:0,208899:0};this.buttons=0;this.keys=[];this.qd=[];this.title=null;this.Wc=this.bd=this.Zc=this.kd=this.Xc=this.Tc=this.fd=this.ce=this.Fd=this.de=this.nd=this.od=0}function pc(){const a=f.canvas;V(a,a.clientWidth,a.clientHeight);ec()}
function qc(){return X.active?0<X.active.attributes[139276]:!1}function rc(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1}
var X={Ic:a=>0>=a||!X.Jc?null:X.Jc[a-1],Rc:0,Ke:0,Te:0,active:null,scale:null,Jc:null,Ve:null,Ue:null,Bd:null,Hd:null,Me:null,Yc:null,Mc:null,Uc:null,ke:{131073:0,131074:0,131075:1,131076:1,131077:1,131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0,139276:0},ee:a=>{switch(a){case 32:return 32;case 222:return 39;case 188:return 44;
case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;
case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;
case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;
case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;
case 18:return 342;case 91:return 343;case 224:return 343;case 93:return 348;default:return-1}},Gd:a=>{var b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);if(a.keys[343]||a.keys[348])b|=8;return b},Sd:a=>{X.active&&X.active.Wc&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||W(X.active.Wc)(X.active.id,a))},vd:(a,b)=>{if(X.active){var c=X.ee(a);if(-1!=c){var d=b&&X.active.keys[c];X.active.keys[c]=b;X.active.qd[a]=b;X.active.bd&&(d&&(b=2),W(X.active.bd)(X.active.id,c,a,b,X.Gd(X.active)))}}},
Qd:()=>{X.wd()},Rd:()=>{X.wd()},Td:a=>{X.vd(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()},Ud:a=>{X.vd(a.keyCode,0)},Kd:()=>{if(X.active)for(var a=0;a<X.active.qd.length;++a)X.active.qd[a]&&X.vd(a,0)},jd:a=>{if(X.active){if("touchmove"===a.type){a.preventDefault();let b=!1;for(let c of a.changedTouches)if(X.Uc===c.identifier){Zb(c.pageX,c.pageY);b=!0;break}if(!b)return}else cc(a);a.target==f.canvas&&X.active.Tc&&X.active.Tc&&W(X.active.Tc)(X.active.id,Ub,Vb)}},fe:a=>{a=a.button;0<
a&&(a=1==a?2:1);return a},Wd:a=>{X.active&&a.target==f.canvas&&X.active.Xc&&W(X.active.Xc)(X.active.id,1)},Xd:a=>{X.active&&a.target==f.canvas&&X.active.Xc&&W(X.active.Xc)(X.active.id,0)},Vd:(a,b)=>{if(X.active&&a.target==f.canvas){var c=0;if("touchstart"===a.type||"touchend"===a.type||"touchcancel"===a.type){a.preventDefault();var d=!1;if(null===X.Uc&&"touchstart"===a.type&&0<a.targetTouches.length)d=a.targetTouches[0],X.Uc=d.identifier,Zb(d.pageX,d.pageY),d=!0;else if("touchend"===a.type||"touchcancel"===
a.type)for(let e of a.changedTouches)if(X.Uc===e.identifier){X.Uc=null;d=!0;break}if(!d)return}else cc(a),c=X.fe(a);if(1==b){X.active.buttons|=1<<c;try{a.target.setCapture()}catch(e){}}else X.active.buttons&=~(1<<c);X.active.fd&&W(X.active.fd)(X.active.id,c,b,X.Gd(X.active))}},gd:a=>{X.active&&X.Vd(a,1)},Sc:a=>{X.active&&X.Vd(a,0)},hd:a=>{switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;
break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);X.Be+=b;if(X.active&&X.active.kd&&a.target==f.canvas){var c=b;b="mousewheel"==a.type?a.wheelDeltaX:a.deltaX;W(X.active.kd)(X.active.id,b,c);a.preventDefault()}},Ld:(a,b,c,d)=>{if(X.active){var e=!1;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?
X.active.ad||(e=a!=screen.width||b!=screen.height,X.active.Yd=X.active.x,X.active.Zd=X.active.y,X.active.yd=X.active.width,X.active.xd=X.active.height,X.active.x=X.active.y=0,X.active.width=screen.width,X.active.height=screen.height,X.active.ad=!0):1==X.active.ad&&(e=a!=X.active.yd||b!=X.active.xd,X.active.x=X.active.Yd,X.active.y=X.active.Zd,X.active.width=X.active.yd,X.active.height=X.active.xd,X.active.ad=!1);if(e)fc(X.active.width,X.active.height);else if(X.active.width!=a||X.active.height!=b||
X.active.sd!=c||X.active.rd!=d)X.active.width=a,X.active.height=b,X.active.sd=c,X.active.rd=d,X.te(),X.re()}},te:()=>{X.active&&X.active.od&&W(X.active.od)(X.active.id,X.active.width,X.active.height)},re:()=>{X.active&&X.active.Fd&&W(X.active.Fd)(X.active.id,X.active.sd,X.active.rd)},se:a=>{X.scale=a;X.active&&X.active.ce&&W(X.active.ce)(X.active.id,X.scale,X.scale)},getTime:()=>hc()/1E3,lf:(a,b)=>{if(a=X.Ic(a))a.title=b,X.active.id==a.id&&(document.title=b?D(q,b):"")},cf:a=>{var b=X.Rc;X.Rc=a;X.wd();
return b},Nc:{},ud:[],Jd:null,wd:()=>{if(Q!==X.Jd||!Q){X.ud=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads||[];X.Jd=Q;for(var a=0;a<X.ud.length;++a){var b=X.ud[a];if(b){X.Nc[a]||(ea("glfw joystick connected:",a),X.Nc[a]={id:L(b.id),Ie:b.buttons.length,He:b.axes.length,buttons:nb(b.buttons.length),axes:nb(4*b.axes.length)},X.Rc&&W(X.Rc)(a,262145));for(var c=X.Nc[a],d=0;d<b.buttons.length;++d)ja[c.buttons+d]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)x[c.axes+4*d>>2]=
b.axes[d]}else X.Nc[a]&&(ea("glfw joystick disconnected",a),X.Rc&&W(X.Rc)(a,262146),sc(X.Nc[a].id),sc(X.Nc[a].buttons),sc(X.Nc[a].axes),delete X.Nc[a])}}},ue:(a,b)=>{a=X.Ic(a);if(!a)return null;var c=a.bd;a.bd=b;return c},Ye:(a,b)=>{a=X.Ic(a);if(!a)return null;var c=a.Wc;a.Wc=b;return c},df:(a,b)=>{a=X.Ic(a);if(!a)return null;var c=a.fd;a.fd=b;return c},$e:(a,b)=>{a=X.Ic(a);if(!a)return null;var c=a.Tc;a.Tc=b;return c},ef:(a,b)=>{a=X.Ic(a);if(!a)return null;var c=a.kd;a.kd=b;return c},af:(a,b)=>{a=
X.Ic(a);if(!a)return null;var c=a.Zc;a.Zc=b;return c},Pd:a=>{if(X.active&&X.active.Zc&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length)return a.preventDefault(),!1},Od:a=>{if(X.active&&X.active.Zc)return a.preventDefault(),!1},ve:(a,b)=>{a=X.Ic(a);if(!a)return null;var c=a.od;a.od=b;return c},gf:(a,b)=>{a=X.Ic(a);if(!a)return null;var c=a.nd;a.nd=b;return c},jf:(a,b)=>{a=X.Ic(a);if(!a)return null;var c=a.de;a.de=b;return c},Md:a=>{!Ib&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),
a.preventDefault())},bf:(a,b,c)=>{if(a=X.Ic(a))switch(b){case 208897:switch(c){case 212993:a.Id[b]=c;f.canvas.removeEventListener("click",X.Md,!0);f.canvas.exitPointerLock();break;case 212994:k("glfwSetInputMode called with GLFW_CURSOR_HIDDEN value not implemented");break;case 212995:a.Id[b]=c;f.canvas.addEventListener("click",X.Md,!0);f.canvas.requestPointerLock();break;default:k(`glfwSetInputMode called with unknown value parameter value: ${c}`)}break;case 208898:k("glfwSetInputMode called with GLFW_STICKY_KEYS mode not implemented");
break;case 208899:k("glfwSetInputMode called with GLFW_STICKY_MOUSE_BUTTONS mode not implemented");break;case 208900:k("glfwSetInputMode called with GLFW_LOCK_KEY_MODS mode not implemented");break;case 3342341:k("glfwSetInputMode called with GLFW_RAW_MOUSE_MOTION mode not implemented");break;default:k(`glfwSetInputMode called with unknown mode parameter value: ${b}`)}},getKey:(a,b)=>(a=X.Ic(a))?a.keys[b]:0,Pe:(a,b)=>(a=X.Ic(a))?0<(a.buttons&1<<b):0,Oe:(a,b,c)=>{la[b>>3]=Ub;la[c>>3]=Vb},Qe:(a,b,c)=>
{r[b>>2]=Ub;r[c>>2]=Vb},Ze:()=>{},Re:(a,b,c)=>{var d=0,e=0;if(a=X.Ic(a))d=a.x,e=a.y;b&&(r[b>>2]=d);c&&(r[c>>2]=e)},hf:(a,b,c)=>{if(a=X.Ic(a))a.x=b,a.y=c},Se:(a,b,c)=>{var d=0,e=0;if(a=X.Ic(a))d=a.width,e=a.height;b&&(r[b>>2]=d);c&&(r[c>>2]=e)},kf:(a,b,c)=>{(a=X.Ic(a))&&X.active.id==a.id&&fc(b,c)},le:()=>{X.Mc=Object.assign({},X.ke)},ie:(a,b,c,d)=>{var e;for(e=0;e<X.Jc.length&&null!==X.Jc[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var g=e+1;if(0>=a||0>=b)return 0;
d?Ob():fc(a,b);for(e=0;e<X.Jc.length&&null==X.Jc[e];e++);a=0<X.Mc[139265];e==X.Jc.length&&(a?f.Qc=Mb(f.canvas,!0,!0,{antialias:1<X.Mc[135181],depth:0<X.Mc[135173],stencil:0<X.Mc[135174],alpha:0<X.Mc[135172]}):Kb());if(!f.Qc&&a)return 0;e=f.canvas;c=new oc(g,e.clientWidth,e.clientHeight,e.width,e.height,c);g-1==X.Jc.length?X.Jc.push(c):X.Jc[g-1]=c;X.active=c;pc();return c.id},me:a=>{if(a=X.Ic(a)){a.nd&&W(a.nd)(a.id);X.Jc[a.id-1]=null;X.active.id==a.id&&(X.active=null);for(a=0;a<X.Jc.length;a++)if(null!==
X.Jc[a])return;f.Qc=void 0}},mf:()=>{},requestFullscreen(a,b){function c(){R=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Pb,T&&d.requestPointerLock(),R=!0,U?Qb():(V(d),ec())):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),U?Rb():(V(d),ec()));if(f.onFullScreen)f.onFullScreen(R);if(f.onFullscreen)f.onFullscreen(R)}T=a;U=b;"undefined"==
typeof T&&(T=!0);"undefined"==typeof U&&(U=!1);var d=f.canvas;Nb||(Nb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):
null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()},Ae(a,b,c){var d=qc()?X.scale:1;b&&c?(a.Cd=b,a.td=c):(b=a.Cd,c=a.td);var e=b,g=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(e/g<f.forcedAspectRatio?e=Math.round(g*f.forcedAspectRatio):g=Math.round(e/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===
a.parentNode&&"undefined"!=typeof screen){var l=Math.min(screen.width/e,screen.height/g);e=Math.round(e*l);g=Math.round(g*l)}U&&(b=e,c=g);e=Math.floor(b*d);d=Math.floor(c*d);a.width!=e&&(a.width=e);a.height!=d&&(a.height=d);"undefined"!=typeof a.style&&(e!=b||d!=c?(a.style.setProperty("width",b+"px","important"),a.style.setProperty("height",c+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height")))},ge(a,b){var c=f.canvas.getBoundingClientRect(),d=f.canvas.clientHeight;
a-=("undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset)+c.left;b-=("undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset)+c.top;a*=f.canvas.clientWidth/c.width;b*=d/c.height;return{x:a,y:b}},ff:(a,b,c)=>{if(a=X.Ic(a)){var d=qc();a.attributes[b]=c;d!==qc()&&pc()}},Nd(){X.se(rc());pc()},Ce:a=>({196609:0,196610:0,196611:0,196612:0,196613:0,196614:0,131073:0,131074:0,131075:0,131076:0,131077:135169,131078:135170,131079:135171,131080:135172,131081:135173,131082:135174,
131083:135183,131084:135175,131085:135176,131086:135177,131087:135178,131088:135179,131089:135180,131090:0,131091:135181,131092:139266,131093:139267,131094:139270,131095:139271,131096:139272})[a]},tc=[31,29,31,30,31,30,31,31,30,31,30,31],uc=[31,28,31,30,31,30,31,31,30,31,30,31];function vc(a){var b=Array(mb(a)+1);A(a,b,0,b.length);return b}for(var J,Y=0;32>Y;++Y)hb.push(Array(Y));var wc=new Float32Array(288);for(Y=0;288>Y;++Y)N[Y]=wc.subarray(0,Y);var xc=new Int32Array(288);
for(Y=0;288>Y;++Y)ub[Y]=xc.subarray(0,Y);f.requestFullscreen=Ob;f.requestAnimationFrame=Tb;f.setCanvasSize=fc;f.pauseMainLoop=function(){O=null;P++};f.resumeMainLoop=function(){P++;var a=Bb,b=Cb,c=zb;zb=null;jc(c,0,!1,Ab,!0);ic(a,b);O()};f.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};f.createContext=Mb;
var yc={Oa:(a,b,c)=>q.copyWithin(a,b,b+c),Ka:function(a,b,c){a=new Date(1E3*(b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN));r[c>>2]=a.getSeconds();r[c+4>>2]=a.getMinutes();r[c+8>>2]=a.getHours();r[c+12>>2]=a.getDate();r[c+16>>2]=a.getMonth();r[c+20>>2]=a.getFullYear()-1900;r[c+24>>2]=a.getDay();r[c+28>>2]=(Da(a.getFullYear())?Ea:Fa)[a.getMonth()]+a.getDate()-1|0;r[c+36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();
r[c+32>>2]=(b!=d&&a.getTimezoneOffset()==Math.min(d,b))|0},Ma:(a,b,c,d)=>{var e=(new Date).getFullYear(),g=new Date(e,0,1),l=new Date(e,6,1);e=g.getTimezoneOffset();var p=l.getTimezoneOffset();v[a>>2]=60*Math.max(e,p);r[b>>2]=Number(e!=p);a=t=>t.toLocaleTimeString(void 0,{hour12:!1,timeZoneName:"short"}).split(" ")[1];g=a(g);l=a(l);p<e?(A(g,q,c,17),A(l,q,d,17)):(A(g,q,d,17),A(l,q,c,17))},Na:()=>Date.now(),K:(a,b,c)=>{a=Pa(a);if(!a)return-4;a=0>Oa.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};
la[b>>3]=a.width;la[c>>3]=a.height;return 0},na:a=>J.activeTexture(a),ma:(a,b)=>{J.attachShader(E[a],H[b])},Fa:(a,b)=>{J.Lc.beginQueryEXT(a,I[b])},la:(a,b,c)=>{J.bindAttribLocation(E[a],b,c?D(q,c):"")},ka:(a,b)=>{J.bindBuffer(a,Va[b])},ja:(a,b)=>{J.bindFramebuffer(a,Wa[b])},ia:(a,b)=>{J.bindRenderbuffer(a,F[b])},ha:(a,b)=>{J.bindTexture(a,G[b])},wa:a=>{J.bindVertexArray(Xa[a])},ga:(a,b,c,d)=>J.blendColor(a,b,c,d),fa:a=>J.blendEquation(a),da:(a,b)=>J.blendEquationSeparate(a,b),ca:(a,b)=>J.blendFunc(a,
b),ba:(a,b,c,d)=>J.blendFuncSeparate(a,b,c,d),aa:(a,b,c,d)=>{J.bufferData(a,c?q.subarray(c,c+b):b,d)},$:(a,b,c,d)=>{J.bufferSubData(a,b,q.subarray(d,d+c))},_:a=>J.checkFramebufferStatus(a),Z:a=>J.clear(a),Y:(a,b,c,d)=>J.clearColor(a,b,c,d),X:a=>J.clearDepth(a),W:a=>J.clearStencil(a),U:(a,b,c,d)=>{J.colorMask(!!a,!!b,!!c,!!d)},T:a=>{J.compileShader(H[a])},S:(a,b,c,d,e,g,l,p)=>{J.compressedTexImage2D(a,b,c,d,e,g,p?q.subarray(p,p+l):null)},R:(a,b,c,d,e,g,l,p,t)=>{J.compressedTexSubImage2D(a,b,c,d,e,
g,l,t?q.subarray(t,t+p):null)},Q:(a,b,c,d,e,g,l,p)=>J.copyTexImage2D(a,b,c,d,e,g,l,p),P:(a,b,c,d,e,g,l,p)=>J.copyTexSubImage2D(a,b,c,d,e,g,l,p),O:()=>{var a=ab(E),b=J.createProgram();b.name=a;b.ed=b.cd=b.dd=0;b.Ad=1;E[a]=b;return a},N:a=>{var b=ab(H);H[b]=J.createShader(a);return b},M:a=>J.cullFace(a),L:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=Va[d];e&&(J.deleteBuffer(e),e.name=0,Va[d]=null)}},J:(a,b)=>{for(var c=0;c<a;++c){var d=r[b+4*c>>2],e=Wa[d];e&&(J.deleteFramebuffer(e),e.name=0,Wa[d]=
null)}},I:a=>{if(a){var b=E[a];b?(J.deleteProgram(b),b.name=0,E[a]=null):K||=1281}},Ha:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=I[d];e&&(J.Lc.deleteQueryEXT(e),I[d]=null)}},H:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=F[d];e&&(J.deleteRenderbuffer(e),e.name=0,F[d]=null)}},G:a=>{if(a){var b=H[a];b?(J.deleteShader(b),H[a]=null):K||=1281}},F:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=G[d];e&&(J.deleteTexture(e),e.name=0,G[d]=null)}},va:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>
2];J.deleteVertexArray(Xa[d]);Xa[d]=null}},E:a=>J.depthFunc(a),D:a=>{J.depthMask(!!a)},C:(a,b)=>J.depthRange(a,b),B:(a,b)=>{J.detachShader(E[a],H[b])},A:a=>J.disable(a),z:a=>{J.disableVertexAttribArray(a)},y:(a,b,c)=>{J.drawArrays(a,b,c)},ra:(a,b,c,d)=>{J.drawArraysInstanced(a,b,c,d)},sa:(a,b)=>{for(var c=hb[a],d=0;d<a;d++)c[d]=r[b+4*d>>2];J.drawBuffers(c)},x:(a,b,c,d)=>{J.drawElements(a,b,c,d)},qa:(a,b,c,d,e)=>{J.drawElementsInstanced(a,b,c,d,e)},w:a=>J.enable(a),v:a=>{J.enableVertexAttribArray(a)},
Ea:a=>{J.Lc.endQueryEXT(a)},u:()=>J.finish(),t:()=>J.flush(),s:(a,b,c,d)=>{J.framebufferRenderbuffer(a,b,c,F[d])},r:(a,b,c,d,e)=>{J.framebufferTexture2D(a,b,c,G[d],e)},q:a=>J.frontFace(a),o:(a,b)=>{bb(a,b,"createBuffer",Va)},m:(a,b)=>{bb(a,b,"createFramebuffer",Wa)},Ia:(a,b)=>{for(var c=0;c<a;c++){var d=J.Lc.createQueryEXT();if(!d){for(K||=1282;c<a;)r[b+4*c++>>2]=0;break}var e=ab(I);d.name=e;I[e]=d;r[b+4*c>>2]=e}},l:(a,b)=>{bb(a,b,"createRenderbuffer",F)},k:(a,b)=>{bb(a,b,"createTexture",G)},ua:(a,
b)=>{bb(a,b,"createVertexArray",Xa)},n:a=>J.generateMipmap(a),j:(a,b,c,d,e,g,l)=>{ib("getActiveAttrib",a,b,c,d,e,g,l)},i:(a,b,c,d,e,g,l)=>{ib("getActiveUniform",a,b,c,d,e,g,l)},h:(a,b,c,d)=>{a=J.getAttachedShaders(E[a]);var e=a.length;e>b&&(e=b);r[c>>2]=e;for(b=0;b<e;++b)r[d+4*b>>2]=H.indexOf(a[b])},g:(a,b)=>J.getAttribLocation(E[a],b?D(q,b):""),f:(a,b)=>jb(a,b,4),xc:(a,b,c)=>{c?r[c>>2]=J.getBufferParameter(a,b):K||=1281},wc:()=>{var a=J.getError()||K;K=0;return a},vc:(a,b)=>jb(a,b,2),uc:(a,b,c,d)=>
{a=J.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;r[d>>2]=a},tc:(a,b)=>jb(a,b,0),rc:(a,b,c,d)=>{a=J.getProgramInfoLog(E[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,q,d,b):0;c&&(r[c>>2]=b)},sc:(a,b,c)=>{if(c)if(a>=Ua)K||=1281;else if(a=E[a],35716==b)a=J.getProgramInfoLog(a),null===a&&(a="(unknown error)"),r[c>>2]=a.length+1;else if(35719==b){if(!a.ed)for(b=0;b<J.getProgramParameter(a,35718);++b)a.ed=Math.max(a.ed,J.getActiveUniform(a,
b).name.length+1);r[c>>2]=a.ed}else if(35722==b){if(!a.cd)for(b=0;b<J.getProgramParameter(a,35721);++b)a.cd=Math.max(a.cd,J.getActiveAttrib(a,b).name.length+1);r[c>>2]=a.cd}else if(35381==b){if(!a.dd)for(b=0;b<J.getProgramParameter(a,35382);++b)a.dd=Math.max(a.dd,J.getActiveUniformBlockName(a,b).length+1);r[c>>2]=a.dd}else r[c>>2]=J.getProgramParameter(a,b);else K||=1281},ya:kb,Ba:lb,xa:kb,za:lb,Ca:(a,b,c)=>{c?r[c>>2]=J.Lc.getQueryEXT(a,b):K||=1281},qc:(a,b,c)=>{c?r[c>>2]=J.getRenderbufferParameter(a,
b):K||=1281},oc:(a,b,c,d)=>{a=J.getShaderInfoLog(H[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,q,d,b):0;c&&(r[c>>2]=b)},mc:(a,b,c,d)=>{a=J.getShaderPrecisionFormat(a,b);r[c>>2]=a.rangeMin;r[c+4>>2]=a.rangeMax;r[d>>2]=a.precision},lc:(a,b,c,d)=>{if(a=J.getShaderSource(H[a]))b=0<b&&d?A(a,q,d,b):0,c&&(r[c>>2]=b)},pc:(a,b,c)=>{c?35716==b?(a=J.getShaderInfoLog(H[a]),null===a&&(a="(unknown error)"),r[c>>2]=a?a.length+1:0):35720==b?(a=J.getShaderSource(H[a]),r[c>>2]=a?a.length+1:0):r[c>>2]=J.getShaderParameter(H[a],
b):K||=1281},kc:a=>{var b=Za[a];if(!b){switch(a){case 7939:b=L(ob().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=J.getParameter(a))||(K||=1280);b=b?L(b):0;break;case 7938:b=L(`OpenGL ES 2.0 (${J.getParameter(7938)})`);break;case 35724:b=J.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=L(b);break;default:K||=1280}Za[a]=b}return b},jc:(a,b,c)=>{c?x[c>>2]=J.getTexParameter(a,
b):K||=1281},ic:(a,b,c)=>{c?r[c>>2]=J.getTexParameter(a,b):K||=1281},fc:(a,b)=>{b=b?D(q,b):"";if(a=E[a]){qb(a);var c=a.Vc,d=0,e=b,g=pb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.ae[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||J.getUniformLocation(a,b)))return d}else K||=1281;return-1},hc:(a,b,c)=>{rb(a,b,c,2)},gc:(a,b,c)=>{rb(a,b,c,0)},bc:(a,b,c)=>{c?r[c>>2]=J.getVertexAttribOffset(a,b):K||=1281},ec:(a,b,c)=>{sb(a,b,c,2)},dc:(a,b,c)=>{sb(a,b,c,5)},ac:(a,b)=>J.hint(a,b),$b:a=>(a=Va[a])?J.isBuffer(a):
0,_b:a=>J.isEnabled(a),Zb:a=>(a=Wa[a])?J.isFramebuffer(a):0,Yb:a=>(a=E[a])?J.isProgram(a):0,Ga:a=>(a=I[a])?J.Lc.isQueryEXT(a):0,Xb:a=>(a=F[a])?J.isRenderbuffer(a):0,Wb:a=>(a=H[a])?J.isShader(a):0,Vb:a=>(a=G[a])?J.isTexture(a):0,ta:a=>(a=Xa[a])?J.isVertexArray(a):0,Ub:a=>J.lineWidth(a),Sb:a=>{a=E[a];J.linkProgram(a);a.Vc=0;a.ae={}},Rb:(a,b)=>{3317==a&&($a=b);J.pixelStorei(a,b)},Qb:(a,b)=>J.polygonOffset(a,b),Da:(a,b)=>{J.Lc.queryCounterEXT(I[a],b)},Pb:(a,b,c,d,e,g,l)=>{(l=tb(g,e,c,d,l))?J.readPixels(a,
b,c,d,e,g,l):K||=1280},Ob:()=>{},Nb:(a,b,c,d)=>J.renderbufferStorage(a,b,c,d),Mb:(a,b)=>{J.sampleCoverage(a,!!b)},Lb:(a,b,c,d)=>J.scissor(a,b,c,d),Kb:()=>{K||=1280},Jb:(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var l=(l=v[c+4*g>>2])?D(q,l,d?v[d+4*g>>2]:void 0):"";e+=l}J.shaderSource(H[a],e)},Hb:(a,b,c)=>J.stencilFunc(a,b,c),Gb:(a,b,c,d)=>J.stencilFuncSeparate(a,b,c,d),Fb:a=>J.stencilMask(a),Eb:(a,b)=>J.stencilMaskSeparate(a,b),Db:(a,b,c)=>J.stencilOp(a,b,c),Cb:(a,b,c,d)=>J.stencilOpSeparate(a,b,c,d),Bb:(a,
b,c,d,e,g,l,p,t)=>{t=t?tb(p,l,d,e,t):null;J.texImage2D(a,b,c,d,e,g,l,p,t)},Ab:(a,b,c)=>J.texParameterf(a,b,c),zb:(a,b,c)=>{J.texParameterf(a,b,x[c>>2])},yb:(a,b,c)=>J.texParameteri(a,b,c),wb:(a,b,c)=>{J.texParameteri(a,b,r[c>>2])},vb:(a,b,c,d,e,g,l,p,t)=>{t=t?tb(p,l,e,g,t):null;J.texSubImage2D(a,b,c,d,e,g,l,p,t)},ub:(a,b)=>{J.uniform1f(M(a),b)},tb:(a,b,c)=>{if(288>=b)for(var d=N[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);J.uniform1fv(M(a),d)},sb:(a,b)=>{J.uniform1i(M(a),b)},
rb:(a,b,c)=>{if(288>=b)for(var d=ub[b],e=0;e<b;++e)d[e]=r[c+4*e>>2];else d=r.subarray(c>>2,c+4*b>>2);J.uniform1iv(M(a),d)},qb:(a,b,c)=>{J.uniform2f(M(a),b,c)},pb:(a,b,c)=>{if(144>=b)for(var d=N[2*b],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);J.uniform2fv(M(a),d)},ob:(a,b,c)=>{J.uniform2i(M(a),b,c)},nb:(a,b,c)=>{if(144>=b)for(var d=ub[2*b],e=0;e<2*b;e+=2)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2];else d=r.subarray(c>>2,c+8*b>>2);J.uniform2iv(M(a),d)},lb:(a,
b,c,d)=>{J.uniform3f(M(a),b,c,d)},kb:(a,b,c)=>{if(96>=b)for(var d=N[3*b],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);J.uniform3fv(M(a),d)},jb:(a,b,c,d)=>{J.uniform3i(M(a),b,c,d)},ib:(a,b,c)=>{if(96>=b)for(var d=ub[3*b],e=0;e<3*b;e+=3)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2],d[e+2]=r[c+(4*e+8)>>2];else d=r.subarray(c>>2,c+12*b>>2);J.uniform3iv(M(a),d)},hb:(a,b,c,d,e)=>{J.uniform4f(M(a),b,c,d,e)},gb:(a,b,c)=>{if(72>=b){var d=N[4*b],
e=x;c>>=2;for(var g=0;g<4*b;g+=4){var l=c+g;d[g]=e[l];d[g+1]=e[l+1];d[g+2]=e[l+2];d[g+3]=e[l+3]}}else d=x.subarray(c>>2,c+16*b>>2);J.uniform4fv(M(a),d)},fb:(a,b,c,d,e)=>{J.uniform4i(M(a),b,c,d,e)},eb:(a,b,c)=>{if(72>=b)for(var d=ub[4*b],e=0;e<4*b;e+=4)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2],d[e+2]=r[c+(4*e+8)>>2],d[e+3]=r[c+(4*e+12)>>2];else d=r.subarray(c>>2,c+16*b>>2);J.uniform4iv(M(a),d)},db:(a,b,c,d)=>{if(72>=b)for(var e=N[4*b],g=0;g<4*b;g+=4)e[g]=x[d+4*g>>2],e[g+1]=x[d+(4*g+4)>>2],e[g+2]=x[d+
(4*g+8)>>2],e[g+3]=x[d+(4*g+12)>>2];else e=x.subarray(d>>2,d+16*b>>2);J.uniformMatrix2fv(M(a),!!c,e)},cb:(a,b,c,d)=>{if(32>=b)for(var e=N[9*b],g=0;g<9*b;g+=9)e[g]=x[d+4*g>>2],e[g+1]=x[d+(4*g+4)>>2],e[g+2]=x[d+(4*g+8)>>2],e[g+3]=x[d+(4*g+12)>>2],e[g+4]=x[d+(4*g+16)>>2],e[g+5]=x[d+(4*g+20)>>2],e[g+6]=x[d+(4*g+24)>>2],e[g+7]=x[d+(4*g+28)>>2],e[g+8]=x[d+(4*g+32)>>2];else e=x.subarray(d>>2,d+36*b>>2);J.uniformMatrix3fv(M(a),!!c,e)},ab:(a,b,c,d)=>{if(18>=b){var e=N[16*b],g=x;d>>=2;for(var l=0;l<16*b;l+=
16){var p=d+l;e[l]=g[p];e[l+1]=g[p+1];e[l+2]=g[p+2];e[l+3]=g[p+3];e[l+4]=g[p+4];e[l+5]=g[p+5];e[l+6]=g[p+6];e[l+7]=g[p+7];e[l+8]=g[p+8];e[l+9]=g[p+9];e[l+10]=g[p+10];e[l+11]=g[p+11];e[l+12]=g[p+12];e[l+13]=g[p+13];e[l+14]=g[p+14];e[l+15]=g[p+15]}}else e=x.subarray(d>>2,d+64*b>>2);J.uniformMatrix4fv(M(a),!!c,e)},$a:a=>{a=E[a];J.useProgram(a);J.je=a},_a:a=>{J.validateProgram(E[a])},Za:(a,b)=>J.vertexAttrib1f(a,b),Ya:(a,b)=>{J.vertexAttrib1f(a,x[b>>2])},Xa:(a,b,c)=>J.vertexAttrib2f(a,b,c),Wa:(a,b)=>
{J.vertexAttrib2f(a,x[b>>2],x[b+4>>2])},Va:(a,b,c,d)=>J.vertexAttrib3f(a,b,c,d),Ua:(a,b)=>{J.vertexAttrib3f(a,x[b>>2],x[b+4>>2],x[b+8>>2])},Ta:(a,b,c,d,e)=>J.vertexAttrib4f(a,b,c,d,e),Ra:(a,b)=>{J.vertexAttrib4f(a,x[b>>2],x[b+4>>2],x[b+8>>2],x[b+12>>2])},oa:(a,b)=>{J.vertexAttribDivisor(a,b)},Qa:(a,b,c,d,e,g)=>{J.vertexAttribPointer(a,b,c,!!d,e,g)},Pa:(a,b,c,d)=>J.viewport(a,b,c,d),La:()=>{ta("OOM")},pa:(a,b,c)=>{a=Pa(a);if(!a)return-4;a.width=b;a.height=c;return 0},Sa:(a,b,c)=>{a=W(a);jc(a,b,c)},
bb:(a,b,c,d)=>mc(a,b,c,d),b:xb,e:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var l=v[b>>2],p=v[b+4>>2];b+=8;for(var t=0;t<p;t++){var y=q[l+t],B=nc[a];0===y||10===y?((1===a?ea:k)(D(B,0)),B.length=0):B.push(y)}e+=p}v[d>>2]=e;return 0},p:(a,b,c,d,e)=>X.ie(a,b,c,d,e),Ja:a=>X.me(a),yc:()=>1,d:()=>X.getTime()-X.Hd,ea:()=>{X.Bd||(X.Bd=L("3.2.1 JS WebGL Emscripten"));return X.Bd},nc:()=>0,V:()=>{if(X.Jc)return 1;X.Hd=X.getTime();X.le();X.Jc=[];X.active=null;X.scale=rc();window.addEventListener("gamepadconnected",
X.Qd,!0);window.addEventListener("gamepaddisconnected",X.Rd,!0);window.addEventListener("keydown",X.Td,!0);window.addEventListener("keypress",X.Sd,!0);window.addEventListener("keyup",X.Ud,!0);window.addEventListener("blur",X.Kd,!0);X.Yc=window.matchMedia("(resolution: "+rc()+"dppx)");X.Yc.addEventListener("change",X.Nd);f.canvas.addEventListener("touchmove",X.jd,!0);f.canvas.addEventListener("touchstart",X.gd,!0);f.canvas.addEventListener("touchcancel",X.Sc,!0);f.canvas.addEventListener("touchend",
X.Sc,!0);f.canvas.addEventListener("mousemove",X.jd,!0);f.canvas.addEventListener("mousedown",X.gd,!0);f.canvas.addEventListener("mouseup",X.Sc,!0);f.canvas.addEventListener("wheel",X.hd,!0);f.canvas.addEventListener("mousewheel",X.hd,!0);f.canvas.addEventListener("mouseenter",X.Wd,!0);f.canvas.addEventListener("mouseleave",X.Xd,!0);f.canvas.addEventListener("drop",X.Pd,!0);f.canvas.addEventListener("dragover",X.Od,!0);Ob=X.requestFullscreen;Yb=X.ge;V=X.Ae;dc.push((a,b)=>{if(qc()){var c=f.canvas;
X.Ld(c.clientWidth,c.clientHeight,a,b)}else X.Ld(a,b,a,b)});return 1},Ib:()=>{},zc:()=>{},Tb:(a,b)=>X.ue(a,b),mb:()=>{},cc:(a,b)=>X.ve(a,b),Aa:()=>{},xb:a=>{a=Math.abs(a);0==a?ic(0,0):ic(1,a)},c:()=>{window.removeEventListener("gamepadconnected",X.Qd,!0);window.removeEventListener("gamepaddisconnected",X.Rd,!0);window.removeEventListener("keydown",X.Td,!0);window.removeEventListener("keypress",X.Sd,!0);window.removeEventListener("keyup",X.Ud,!0);window.removeEventListener("blur",X.Kd,!0);f.canvas.removeEventListener("touchmove",
X.jd,!0);f.canvas.removeEventListener("touchstart",X.gd,!0);f.canvas.removeEventListener("touchcancel",X.Sc,!0);f.canvas.removeEventListener("touchend",X.Sc,!0);f.canvas.removeEventListener("mousemove",X.jd,!0);f.canvas.removeEventListener("mousedown",X.gd,!0);f.canvas.removeEventListener("mouseup",X.Sc,!0);f.canvas.removeEventListener("wheel",X.hd,!0);f.canvas.removeEventListener("mousewheel",X.hd,!0);f.canvas.removeEventListener("mouseenter",X.Wd,!0);f.canvas.removeEventListener("mouseleave",X.Xd,
!0);f.canvas.removeEventListener("drop",X.Pd,!0);f.canvas.removeEventListener("dragover",X.Od,!0);X.Yc&&X.Yc.removeEventListener("change",X.Nd);f.canvas.width=f.canvas.height=1;X.Jc=null;X.active=null},a:(a,b)=>{X.Mc[a]=b},Ac:(a,b,c,d)=>{function e(m,u,w){for(m="number"==typeof m?m.toString():m||"";m.length<u;)m=w[0]+m;return m}function g(m,u){return e(m,u,"0")}function l(m,u){function w($b){return 0>$b?-1:0<$b?1:0}var S;0===(S=w(m.getFullYear()-u.getFullYear()))&&0===(S=w(m.getMonth()-u.getMonth()))&&
(S=w(m.getDate()-u.getDate()));return S}function p(m){switch(m.getDay()){case 0:return new Date(m.getFullYear()-1,11,29);case 1:return m;case 2:return new Date(m.getFullYear(),0,3);case 3:return new Date(m.getFullYear(),0,2);case 4:return new Date(m.getFullYear(),0,1);case 5:return new Date(m.getFullYear()-1,11,31);case 6:return new Date(m.getFullYear()-1,11,30)}}function t(m){var u=m.Oc;for(m=new Date((new Date(m.Pc+1900,0,1)).getTime());0<u;){var w=m.getMonth(),S=(Da(m.getFullYear())?tc:uc)[w];
if(u>S-m.getDate())u-=S-m.getDate()+1,m.setDate(1),11>w?m.setMonth(w+1):(m.setMonth(0),m.setFullYear(m.getFullYear()+1));else{m.setDate(m.getDate()+u);break}}w=new Date(m.getFullYear()+1,0,4);u=p(new Date(m.getFullYear(),0,4));w=p(w);return 0>=l(u,m)?0>=l(w,m)?m.getFullYear()+1:m.getFullYear():m.getFullYear()-1}var y=v[d+40>>2];d={ye:r[d>>2],xe:r[d+4>>2],ld:r[d+8>>2],zd:r[d+12>>2],md:r[d+16>>2],Pc:r[d+20>>2],Kc:r[d+24>>2],Oc:r[d+28>>2],pf:r[d+32>>2],we:r[d+36>>2],ze:y?y?D(q,y):"":""};c=c?D(q,c):"";
y={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var B in y)c=c.replace(new RegExp(B,"g"),y[B]);var ac="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
bc="January February March April May June July August September October November December".split(" ");y={"%a":m=>ac[m.Kc].substring(0,3),"%A":m=>ac[m.Kc],"%b":m=>bc[m.md].substring(0,3),"%B":m=>bc[m.md],"%C":m=>g((m.Pc+1900)/100|0,2),"%d":m=>g(m.zd,2),"%e":m=>e(m.zd,2," "),"%g":m=>t(m).toString().substring(2),"%G":t,"%H":m=>g(m.ld,2),"%I":m=>{m=m.ld;0==m?m=12:12<m&&(m-=12);return g(m,2)},"%j":m=>{for(var u=0,w=0;w<=m.md-1;u+=(Da(m.Pc+1900)?tc:uc)[w++]);return g(m.zd+u,3)},"%m":m=>g(m.md+1,2),"%M":m=>
g(m.xe,2),"%n":()=>"\n","%p":m=>0<=m.ld&&12>m.ld?"AM":"PM","%S":m=>g(m.ye,2),"%t":()=>"\t","%u":m=>m.Kc||7,"%U":m=>g(Math.floor((m.Oc+7-m.Kc)/7),2),"%V":m=>{var u=Math.floor((m.Oc+7-(m.Kc+6)%7)/7);2>=(m.Kc+371-m.Oc-2)%7&&u++;if(u)53==u&&(w=(m.Kc+371-m.Oc)%7,4==w||3==w&&Da(m.Pc)||(u=1));else{u=52;var w=(m.Kc+7-m.Oc-1)%7;(4==w||5==w&&Da(m.Pc%400-1))&&u++}return g(u,2)},"%w":m=>m.Kc,"%W":m=>g(Math.floor((m.Oc+7-(m.Kc+6)%7)/7),2),"%y":m=>(m.Pc+1900).toString().substring(2),"%Y":m=>m.Pc+1900,"%z":m=>{m=
m.we;var u=0<=m;m=Math.abs(m)/60;return(u?"+":"-")+String("0000"+(m/60*100+m%60)).slice(-4)},"%Z":m=>m.ze,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(B in y)c.includes(B)&&(c=c.replace(new RegExp(B,"g"),y[B](d)));c=c.replace(/\0\0/g,"%");B=vc(c);if(B.length>b)return 0;ja.set(B,a);return B.length-1}},Z=function(){function a(c){Z=c.exports;ha=Z.Bc;c=ha.buffer;f.HEAP8=ja=new Int8Array(c);f.HEAP16=new Int16Array(c);f.HEAPU8=q=new Uint8Array(c);f.HEAPU16=ka=new Uint16Array(c);f.HEAP32=r=new Int32Array(c);
f.HEAPU32=v=new Uint32Array(c);f.HEAPF32=x=new Float32Array(c);f.HEAPF64=la=new Float64Array(c);lc=Z.Gc;na.unshift(Z.Cc);z--;f.monitorRunDependencies?.(z);0==z&&(null!==ra&&(clearInterval(ra),ra=null),sa&&(c=sa,sa=null,c()));return Z}var b={a:yc};z++;f.monitorRunDependencies?.(z);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return k(`Module.instantiateWasm callback failed with error: ${c}`),!1}va||=ua("index.wasm")?"index.wasm":f.locateFile?f.locateFile("index.wasm",h):h+"index.wasm";
za(b,function(c){a(c.instance)});return{}}(),nb=a=>(nb=Z.Dc)(a),sc=a=>(sc=Z.Ec)(a),zc=f._main=(a,b)=>(zc=f._main=Z.Fc)(a,b),Ac=a=>(Ac=Z.Hc)(a),Bc;sa=function Cc(){Bc||Dc();Bc||(sa=Cc)};function Ec(a=[]){var b=zc;a.unshift(ca);var c=a.length,d=Ac(4*(c+1)),e=d;a.forEach(l=>{var p=v,t=e>>2,y=mb(l)+1,B=Ac(y);A(l,q,B,y);p[t]=B;e+=4});v[e>>2]=0;try{var g=b(c,d);xb(g,!0)}catch(l){vb(l)}}
function Dc(){var a=ba;function b(){if(!Bc&&(Bc=!0,f.calledRun=!0,!n)){Ba(na);Ba(oa);if(f.onRuntimeInitialized)f.onRuntimeInitialized();Fc&&Ec(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();pa.unshift(c)}Ba(pa)}}if(!(0<z)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)qa();Ba(ma);0<z||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},
1)):b())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Fc=!0;f.noInitialRun&&(Fc=!1);Dc();
